### ISSUE TITLE
Composer update Issue

### ISSUE THREAD

**Issue by lifewaypn** [Zzzul/generator#33]
When I trying to Update Package through composer error on 

> "Problem 1
>     - Root composer.json requires zzzul/generator, it could not be found in any version, there may be a typo in the package name.

please solve this issue

**Comment by Zzzul** [comment]
This is because I transferred the repository to https://github.com/Evdigi-INA/generator, so please check and update your composer.json immediately.
Kindly update your composer.json file.
```sh 
"zzzul/generator": "^0.1.1"
``` 
to 
```sh
"evdigiina/generator": "dev-dev",
```

**Comment by ghost** [comment]
What are doing sir, why did you add "evdigiina/generator:dev" in composer, you already added in Main Project

**Comment by Zzzul** [comment]
I recently modified the repository, previously it was "zzzul/generator"
If you have already cloned this repository, please update to acquire the most recent version.

**Comment by Zzzul** [comment]
If the issue persists, the easiest solution is to utilize the package that you can use without cloning this repository, simply install it similarly to any other package.

Here is the package, https://github.com/Evdigi-INA/generator to install it, run it in your terminal with the command below
```sh
composer require evdigiina/generator:dev-dev --dev
```
Next is to follow the steps in the [README.md](https://github.com/Evdigi-INA/generator/tree/dev#readme)
